### PR TITLE
Upgrade Zoom.VariableZoom to contain list of zoom ratios supported by camera

### PR DESCRIPTION
**Pull request by johnnymartinovic**

### CODE REVIEW

**Comment by johnnymartinovic** [comment]
@dmitry-zaitsev hi, sry to bother you. Could you please tell me when could this be checked and merged?

**Comment by dmitry-zaitsev** [comment]
Hi, sorry for the delay and thanks for brining this up. I will check it on
Sumday (08.09).

**Comment by dmitry-zaitsev** [comment]
@johnnymartinovic merged now. Thanks for the contribution!

**Comment by dmitry-zaitsev** [comment]
This change published as part of 2.4.0 release

**Comment by johnnymartinovic** [comment]
great, tnx!

**Comment by johnnymartinovic** [comment]
@dmitry-zaitsev hi, which version with all the new updates will be released and when?

**Pull request merged**
